import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Trello 2.0',
  description: 'Generated by InnovDs',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg- '>
        {children}
        <Modal />
        </body>
    </html>
  )
}
